[package]
name = "web-assembly-test"
version = "0.1.0"
edition = "2021"
authors = ["Marcuth <you@example.com>"]
description = "Um pequeno teste para matar a curiosidade..."

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"